name: release
on:
  release:
    types: [published, edited]
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: setup
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: restore
      run: dotnet restore

    - name: build
      run: dotnet build --configuration Release --no-restore

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/checkout@v4
    - name: setup
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
      
    - name: test
      run: dotnet test "test/UnitTest.csproj" /p:CollectCoverage=true /p:CoverletOutputFormat=opencover

  publish:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - uses: actions/checkout@v4
    - name: setup
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: dotnet pack
      run: dotnet pack "src/Core.csproj" /p:PackageVersion=${{ github.ref_name }} -c Release -o ./dist

    - name: nuget publish
      run: dotnet nuget push "./dist/*.nupkg" -k ${{ secrets.NUGET_TOKEN }} -s ${{ secrets.NUGET_SOURCE }}